export const GET_PHONES_START = 'PHONES/GET/START';
export const GET_PHONES_SUCCESS = 'PHONES/GET/SUCCESS';
export const GET_PHONES_FAIL = 'PHONES/GET/FAIL';
export const SET_SELECTED_PHONE = 'PHONE/SET/SELECTED';
export const REMOVE_SELECTED_PHONE = 'PHONE/REMOVE/SELECTED';