export const GET_PHONES_START = 'PHONES/GET/START';
export const GET_PHONES_SUCCESS = 'PHONES/GET/SUCCESS';
export const GET_PHONES_FAIL = 'PHONES/GET/FAIL';
export const GET_PHONE_DETAILS = 'PHONE/GET/DETAILS';
export const REMOVE_PHONE_DETAILS = 'PHONE/REMOVE/DETAILS';